zsh tweaks for macos

diff --git a/dotfiles/zshrc b/dotfiles/zshrc
--- a/dotfiles/zshrc
+++ b/dotfiles/zshrc
@@ -110,3 +110,26 @@ exec-new-zsh() {
 
 zle -N exec-new-zsh
 bindkey '^N' exec-new-zsh
+
+#
+# source local zsrc.d/* files if they exist
+#
+
+typeset -ga _zshrcd=(
+  $ZSHRCD
+  ${ZDOTDIR:-/dev/null}/zshrc.d(N)
+  ${HOME}/.zshrc.d(N)
+  ${ZDOTDIR:-$HOME}/.config/zsh/zshrc.d(N)
+)
+if [[ ! -e "$_zshrcd[1]" ]]; then
+  echo >&2 "zshrc.d: dir not found HOME or ZDOTDIR path!"
+  return 1
+fi
+
+typeset -ga _zshrcd=("$_zshrcd[1]"/*.{sh,zsh}(N))
+typeset -g _zshrcd_file
+for _zshrcd_file in ${(o)_zshrcd}; do
+  [[ ${_zshrcd_file:t} != '~'* ]] || continue  # ignore tilde files
+  source "$_zshrcd_file"
+done
+unset _zshrcd{,_file}
